docs(transform): control
EasyBrizy/Brizy-Local-Editor pull request #256
Opened 2024-06-03 08:38 UTC by CristianSpatari

2024-06-03 12:18 UTC, victor-pg requested changes

2024-06-03 12:18 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/data-controls/transform.md
> +  value: string;
why here is only 1 key is transform returns many keys ?

2024-06-03 12:18 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/data-controls/transform.md
> +| `config?.disabled`        | `boolean`
about `config.disabled`

this is another props, not `disabled` from every option

`config.disabled` from your control is an array

2024-06-03 12:18 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/data-controls/transform.md
> +| `type`                    | `string`
about "Type should be `"inputText"` to use this control"

why inputText ? set your control name

2024-06-03 12:18 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/data-controls/transform.md
> +}
only this example ?

2024-06-04 13:59 UTC, victor-pg requested changes
1. Move it to multivalue controls
![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/1d167003-a502-4082-8c8d-3653903efc58)
2. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/0b5d4afc-6838-45a3-8ba0-a79172b9c6b6)
3. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/501de424-05e8-40dd-89aa-da769668c5e0)
4. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/53832c8b-8c3c-42b0-9e21-af310ec12377)
5.

2024-06-04 13:59 UTC, victor-pg commented on docusaurus/static/img/data-controls/transform.png
move it to multivalue folder

2024-06-05 12:13 UTC, victor-pg requested changes
Need to describe it as how described @grandleemon in `Motion`
![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/9383253b-dcb6-4d3b-b2f8-c3efe2f7c19e)

2024-06-06 06:27 UTC, victor-pg requested changes
How your transform works with this effects ?

![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/6a889728-d1b8-4823-9538-45578c5352c1)

As example `mouseTilt`, how it supposed to be disabled if your transform has no `mouseTilt` property

2024-06-06 06:27 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/multivalue-controls/transform.md
> +}
How look your return value: 
![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/0310376f-2acf-4e24-9d43-754f606726a7)

Make your return value and return value description look like in this PR: https://github.com/EasyBrizy/Brizy-Local-Editor/pull/259/files#diff-1f4f17d8adb93cf89a4dbfa84cd9eb9668f165d122ffefaf231f012982ab25bdR31-R46

2024-06-06 11:55 UTC, victor-pg requested changes
1. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/76b186da-5319-415d-aa28-fbd1c8245a7c)
2. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/ef04703d-07ba-4a77-b2d7-907f88f4a41f)

2024-06-07 10:41 UTC, CristianSpatari commented
> 1. ![image](https://private-user-images.githubusercontent.com/52622998/337252470-76b186da-5319-415d-aa28-fbd1c8245a7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTY1NTIsIm5iZiI6MTcxNzc1NjI1MiwicGF0aCI6Ii81MjYyMjk5OC8zMzcyNTI0NzAtNzZiMTg2ZGEtNTMxOS00MTVkLWFhMjgtZmJkMWM4MjQ1YTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEwMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzZWU3YjM5YWVjMTBlYTg1NDdmZDU0MjFhNmQyYTE4ZTExYzM2YjgyZGVmZTcyOWY2OWYwODE4YTg3NzY4YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GdfkVu43g7eQFC7O0Qvj7Myinah0mQWNFjk7ydAMHYA)
> 2. ![image](https://private-user-images.githubusercontent.com/52622998/337253144-ef04703d-07ba-4a77-b2d7-907f88f4a41f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NTY1NTIsIm5iZiI6MTcxNzc1NjI1MiwicGF0aCI6Ii81MjYyMjk5OC8zMzcyNTMxNDQtZWYwNDcwM2QtMDdiYS00YTc3LWIyZDctOTA3Zjg4ZjRhNDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDEwMzA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY1NzZhMjgzNDM3M2ExNzk4ZWNiMzE0NzZkZmU1M2M2ZjUxNzk2YzcwYTFhYTk2M2RiOWQ5OGY4NTU3YTQwZjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WmfNVtOWqJdq1xu93-yDHr5kAGQuunvT0SGwfIPHWyU)

Because no disabled 
![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/107267475/33294e77-0a06-4b83-878e-ab6f15b3bbbc)

2024-06-19 07:13 UTC, merged