docs(internalLink): control
EasyBrizy/Brizy-Local-Editor pull request #257
Opened 2024-06-03 13:08 UTC by CristianSpatari

2024-06-04 06:39 UTC, victor-pg requested changes
1. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/c5a75f8c-12cf-4e2a-8926-42b28b474d81)
2. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/3c0f4b58-c1dc-4aff-8e7e-4b6d1ce844bf)
3. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/4d2c6e93-9eb5-4758-a5e6-56d319ed1e54)
4. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/ea10ba0c-88c5-4271-9038-8fce1bba6d2b)

2024-06-04 06:39 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/data-controls/internalLink.md
> +### Parameters
`internalLink` has also the `placeholder` props
![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/7a5f9a73-3b74-46a1-97fd-19a5f004330d)

check if component can render it or how is used and if is needed then add it to parameters table

2024-06-04 14:18 UTC, victor-pg requested changes
1. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/a50d6663-99c3-474b-ae26-a3f0bdca130c)
2. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/2e352698-3d19-4316-bb3a-27591e7acf96)
3. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/debff286-b79c-41c9-aa39-ea2334b05e4c)

2024-06-05 12:52 UTC, victor-pg requested changes
1. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/7d1ee444-a1c7-46b5-9b17-0a70424bbc8b)
2. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/ed9bb715-fd0e-4307-be1f-84e8d4433f9f)

2024-06-06 06:54 UTC, CristianSpatari commented
> 1. ![image](https://private-user-images.githubusercontent.com/52622998/336843102-7d1ee444-a1c7-46b5-9b17-0a70424bbc8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTcxMzUsIm5iZiI6MTcxNzY1NjgzNSwicGF0aCI6Ii81MjYyMjk5OC8zMzY4NDMxMDItN2QxZWU0NDQtYTFjNy00NmI1LTliMTctMGE3MDQyNGJiYzhiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA2NTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwMzBmOTRmYmJkMDZhZDYyY2Y4OWIxMmJmYzFhYWM2M2RmMTY0NGZmMGQwNDI5NmVmZDVkMTY0YTY3ZTZkNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6XZyNzwTzeQouSVQhzsxQzO1iPn3g5l93OEI6XeUx1k)
> 2. ![image](https://private-user-images.githubusercontent.com/52622998/336843501-ed9bb715-fd0e-4307-be1f-84e8d4433f9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2NTcxMzUsIm5iZiI6MTcxNzY1NjgzNSwicGF0aCI6Ii81MjYyMjk5OC8zMzY4NDM1MDEtZWQ5YmI3MTUtZmQwZS00MzA3LWJlMWYtODRlOGQ0NDMzZjlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDA2NTM1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ1NDVjZDg4N2FkNThiZDNhZjI0MTc0ZWUzMGI0MGMzOWQ5Y2FiNjlmYThiZjdmZTU1ZGQ1N2IyZWE2ZGYwM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zU4vb1lWmerIEDGKCKPdIaVLqcQSy_eZk-U9nSjRY_g)

Aici helper se arunca prin config. Nu stiu ce exemplu sa mai scriu

2024-06-06 07:25 UTC, victor-pg requested changes
1. Broken table
![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/39fb7520-b2a1-4655-9636-b1ca352ebfef)
2. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/d5f3d3b8-1055-48c7-8fd4-026c6f3ca6ae)
3. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/486abaf5-6d5c-4f6e-bb66-507a7be68cb6)

2024-06-06 07:25 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/data-controls/internalLink.md
> +`value`: A string that holds the actual data or content. <br/>
value: the actual selected value
title: the label of the selected value
source: /* here describe that the source is the collection from where we try to find a link */

2024-06-06 12:33 UTC, victor-pg requested changes
1. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/27b7ad70-cfb6-48ea-afbd-7f71d70b66f2)
2. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/ff0836b5-9967-4e3c-822b-e9e17bf7ed36)

2024-06-11 07:27 UTC, merged