typography extend
EasyBrizy/Brizy-Local-Editor pull request #315
Opened 2024-06-21 08:05 UTC by grandleemon

2024-06-21 08:06 UTC, grandleemon commented on docusaurus/docs-internals/editor-controls/multivalue-controls/typography.md
> +```
doesn't work in edtiro

2024-06-21 08:14 UTC, grandleemon commented on docusaurus/docs-internals/editor-controls/multivalue-controls/typography.md
> +```
`style` doesn't trigger in editor

2024-06-21 10:49 UTC, victor-pg requested changes
Fix the error because doc are not running

[Screencast from 06-21-2024 01:47:34 PM.webm](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/e184b18c-dd2a-4e0b-bcee-0c88c1a6d3a6)

2024-06-25 08:24 UTC, victor-pg requested changes
1. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/8f032927-65a3-47f7-b593-ae598a714dcd)
2. `style` is triggered:

[Screencast from 06-25-2024 11:16:45 AM.webm](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/b3dc06ab-fbb3-4665-bb61-65837e23021c)

3. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/e45c2de5-7da0-44e4-971c-3926beecb729)
4. Missing `selector` in parameters + example
5. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/2f403cd3-a07e-4229-88fd-7c1bd17c1ac2)
6. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/20c8f8b4-d380-4cc6-85ed-2ac69d94755a)

2024-06-27 09:44 UTC, merged