docs(tabs): control
EasyBrizy/Brizy-Local-Editor pull request #324
Opened 2024-06-25 08:18 UTC by CristianSpatari

2024-06-25 14:35 UTC, victor-pg requested changes
1. Your control can't handle `className` and `icon`
2. Remove `states` and `display` parameters
---
![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/0a9681ec-47e9-4d1c-b4b8-863c7f5224b2)

2024-06-28 11:43 UTC, victor-pg requested changes

2024-06-28 11:43 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/group-controls/tabs.md
> +}
you have only 1 props: `tabsColor`

2024-06-28 11:43 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/group-controls/tabs.md
> +}
```ts
{
  id: "actionTabs",
  type: "tabs",
  style: ({ value }) => {

    if (value && value.value === "tabIcon") {
      return {
        ".brz-container.brz-tab-color": {
          display: "none"
        }
      }
    }

    return {
      ".brz-container.brz-tab": {
        display: "block"
      }
    }
  }
}
```

create similar example for `style` from parameters table

2024-06-28 11:43 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/group-controls/tabs.md
> +      <a href =${value} rel="blank|self"/>
invalid html

2024-06-28 11:43 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/group-controls/tabs.md
> +    </div>
write an example where you render something when some tab is active:
```ts
<div>
{ asd === "tabColor" && <ASdCOmponent/> }
</div>
```

2024-07-01 06:32 UTC, victor-pg requested changes
1. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/dcd40792-a322-4610-87bc-a449d6d2c554)
---
2. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/0822afeb-ff78-48a6-81ef-6e86b6e2233e)

2024-07-01 06:32 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/group-controls/tabs.md
> +| `selector?` | `string`         | - | The CSS selector to which the styles will be applied
`tabs` doesn't have `selector` properties, so remove this and don't forget to remove also examples with `selector`

2024-07-01 06:32 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/group-controls/tabs.md
> +| `style?` | `function`       | - | This function generates CSS output based on the value from the control. The parameter is an object containing a `value` key, which holds the current value of the c
"external" -> "tabExternal"

2024-07-01 06:32 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/group-controls/tabs.md
> +  value: string;
invalid key, no options will return the `value`

2024-07-01 06:32 UTC, victor-pg commented on docusaurus/docs-internals/editor-controls/group-controls/tabs.md
> +      { value === "tabsColor" && <Button/> }
prettify

2024-07-01 08:43 UTC, CristianSpatari commented
> 1. ![image](https://private-user-images.githubusercontent.com/52622998/344567250-dcd40792-a322-4610-87bc-a449d6d2c554.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjAxMDMsIm5iZiI6MTcxOTgxOTgwMywicGF0aCI6Ii81MjYyMjk5OC8zNDQ1NjcyNTAtZGNkNDA3OTItYTMyMi00NjEwLTg3YmMtYTQ0OWQ2ZDJjNTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA3NDMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMDdjMjliNWQxODhkYzg4ODMwZWFjOGQwY2FmZDg3MTNlZDhmNGE2Y2Q3NzgzYTc3Mzc4MDExMDQzMzUwNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7NydbpruJ91yWi0F_G60vMABwGc0tpA2Lda_220t3pU)
> 
> 2. ![image](https://private-user-images.githubusercontent.com/52622998/344567554-0822afeb-ff78-48a6-81ef-6e86b6e2233e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MjAxMDMsIm5iZiI6MTcxOTgxOTgwMywicGF0aCI6Ii81MjYyMjk5OC8zNDQ1Njc1NTQtMDgyMmFmZWItZmY3OC00OGE2LTgxZWYtNmU4NmI2ZTIyMzNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDA3NDMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwZDdiZWFjZDgyMDc2YjY3ZTJmM2FjNDZlMDVkYzhiY2FhZTliYzIxZjRkZjg3OGQ5YzBmZmYzNmZmMGEwYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7t2muGd6hhVw3pcGATxYh46rGG4Xx1hMSk-FnENIR_Q)

1. Referitor la ";" chat GPT parca spune ca e ok si nu prea are ceva obiectii.

2024-07-01 10:50 UTC, victor-pg requested changes
1. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/13affaf1-049d-4792-b620-732c082cf9af)
---
2. ![image](https://github.com/EasyBrizy/Brizy-Local-Editor/assets/52622998/42072fe4-ede1-4777-9ddb-d7a37015e132)
---
3. ![Uploading image.png…]()

2024-07-29 08:39 UTC, merged