feat(cms): added product pages
EasyBrizy/Brizy-Local-Editor pull request #405
Opened 2024-08-20 08:57 UTC by nicolaisirghi

2024-08-21 14:16 UTC, maxval1 requested changes

2024-08-21 14:16 UTC, maxval1 commented on packages/demo-nextjs/src/components/Metronic/modules/apps/products/components/table/columns/ProductActionsCell.tsx
> +const SHOPIFY_BASE_URL = "https://admin.shopify.com/store";
move inside `utils/mock.ts`

2024-08-21 14:16 UTC, maxval1 commented on packages/demo-nextjs/src/components/Metronic/modules/apps/products/core/ProductsProvider.tsx
> +      const collectionType = "product";
use enum

2024-08-21 14:16 UTC, maxval1 commented on packages/demo-nextjs/src/components/Metronic/modules/apps/products/core/_requests.ts
> +const API_URL = `${getConfig().host}/api`;
remove `getConfig().host` use `/api`

2024-08-22 06:36 UTC, nicolaisirghi commented on packages/demo-nextjs/src/app/[[...slug]]/page.tsx
> +const excludeCatchAllCollection = [ CollectionTypes.popup, CollectionTypes.story];
If I correctly understand the usage of the `excludeCatchAllCollection`, is for exclude the preview for items with the specific collection.

 Now, it also needs to include the system page for Product in the preview.
![image](https://github.com/user-attachments/assets/74556294-5bd6-43e6-925c-7b7ed5bbb9ae)

2024-08-22 10:24 UTC, maxval1 requested changes

2024-08-22 10:24 UTC, maxval1 commented on packages/demo-nextjs/src/app/admin/(editor)/product/[slug]/page.tsx
> +  const pagePreview = `${getConfig().host}/product/${slug}`;
![image](https://github.com/user-attachments/assets/f8f36faf-9796-4137-87bf-88133cb60b1e)

2024-08-29 06:25 UTC, maxval1 requested changes
Conflcits

2024-09-03 06:53 UTC, merged