feat(editor): added shopify elements and placeholders for them
EasyBrizy/Brizy-Local-Editor pull request #410
Opened 2024-08-21 07:16 UTC by nicolaisirghi

### Changelog
- New: Added shopify elements in editor

2024-08-21 14:25 UTC, maxval1 requested changes

2024-08-21 14:25 UTC, maxval1 commented on packages/core/src/core.ts
> +              handler?.(res, rej, extra);
remove the `?`

2024-08-22 07:45 UTC, nicolaisirghi commented on packages/core/src/types/types.ts
> +  reference?: Reference;
Tell me when will be needed to discuss

2024-08-22 11:02 UTC, maxval1 commented on packages/demo-nextjs/src/lib/editorConfig/index.ts
> +  const reference = JSON.parse(model.config?.reference ?? "{}");
rollback

2024-09-05 11:24 UTC, maxval1 requested changes
Small PR

2024-09-05 11:24 UTC, maxval1 commented on packages/thirdparty-widgets/src/Cart/export/addToCart.ts
> +import { getAddToCartData, reinitializeCarts, showUserErrors } from "./utils";
need to review

2024-09-05 11:24 UTC, maxval1 commented on packages/thirdparty-widgets/src/Cart/export/constants.ts
> +export const DEFAULT_TITLE = "Default Title";
review

2024-09-05 11:24 UTC, maxval1 commented on packages/thirdparty-widgets/src/Cart/export/index.ts
> +import { getCart } from "./requests";
review

2024-09-05 11:24 UTC, maxval1 commented on packages/thirdparty-widgets/src/Cart/export/requests.ts
> +export const addItemToCart = ({
review

2024-09-05 11:24 UTC, maxval1 commented on packages/thirdparty-widgets/src/Cart/export/utils.ts
> +const toggleClass = (element: HTMLElement, className: string, add: boolean) =>
review

2024-09-05 11:24 UTC, maxval1 commented on packages/thirdparty-widgets/src/components/ThemeIcon/index.tsx
> +const ThemeIconPreview = (props: Props): JSX.Element => {
need to review
1. Documentation
2. How we can use it from the Editor(edit, view mode)

2024-09-06 06:41 UTC, maxval1 requested changes

2024-09-06 06:41 UTC, maxval1 commented on packages/demo-nextjs/src/placeholders/types/BuilderPlaceholder.ts
> +    return `{{${placeholderName} ${attrStr}}}`;
extract plachodelr via sdk

2024-09-11 06:50 UTC, merged