27059 refactor dashboard cms
EasyBrizy/Brizy-Local-Editor pull request #413
Opened 2024-08-21 12:38 UTC by nicolaisirghi

2024-08-22 05:50 UTC, GunkaArtur approved these changes

2024-08-26 06:01 UTC, maxval1 commented on packages/demo-nextjs/src/app/api/items/latest/route.ts
> +    await DBConnect();
remove `await DBConnect`

2024-08-26 06:02 UTC, maxval1 commented on packages/demo-nextjs/src/app/api/items/latest/route.ts
> +    const { items } = await getItems({}, { sort: { createdAt: -1 }, limit: parseInt(limit ?? "5"), skip: 0 });
need to chage the interface of getItems, need to ad `sortBy: "date" | "name"` and `sort: "desc" | "asc"`

2024-08-29 06:23 UTC, maxval1 requested changes
conflicts

2024-08-30 06:04 UTC, maxval1 requested changes

2024-08-30 06:04 UTC, maxval1 commented on packages/demo-nextjs/src/lib/db/item/getItems.ts
> +  type?: string;
Need to create 2 types something like this
![image](https://github.com/user-attachments/assets/b384681f-69da-4b75-b50d-de383d49162c)

2024-09-03 06:35 UTC, merged