feat(system): added seo and custom code functionality
EasyBrizy/Brizy-Local-Editor pull request #449
Opened 2024-09-23 06:43 UTC by nicolaisirghi

2024-09-25 07:10 UTC, maxval1 requested changes

2024-09-25 07:10 UTC, maxval1 commented on packages/demo-nextjs/src/app/admin/(cms)/system/core/requests.ts
> +  const origin = getOrigin(headersList);
move `headers()` inside getOrigin() add move `use server` inside  `getOrigin()`

2024-09-26 06:49 UTC, maxval1 requested changes

2024-09-26 06:49 UTC, maxval1 commented on packages/demo-nextjs/src/utils/origin.ts
> +export async function getOrigin(): Promise<string> {
remove `async`

2024-09-26 13:19 UTC, nicolaisirghi commented on packages/demo-nextjs/src/utils/origin.ts
> +export async function getOrigin(): Promise<string> {
![image](https://github.com/user-attachments/assets/9a1ff716-87c1-43ad-93a0-37b537e32554)

2024-09-27 04:34 UTC, merged