fix(preview): styles are inserted in wrong order in head
EasyBrizy/Brizy-Local-Editor pull request #507
Opened 2024-12-27 10:37 UTC by nicolaisirghi

2025-01-21 14:35 UTC, maxval1 requested changes

2025-01-21 14:35 UTC, maxval1 commented on packages/demo-nextjs/src/app/layout.tsx
> +      <body className="brz" {...defaultThemeAttr}>{children}</body>
needs to review

2025-01-21 14:35 UTC, maxval1 commented on packages/demo-nextjs/src/utils/index.ts
> +  //@ts-expect-error Type "file" is not assignable to type AssetType.File
needs to review

2025-01-21 14:35 UTC, maxval1 commented on packages/demo-nextjs/src/utils/makeAssets.tsx
> +import { DomUtils, parseDocument } from "htmlparser2";
need to review

2025-01-23 12:05 UTC, nicolaisirghi commented on packages/demo-nextjs/src/app/layout.tsx
> +      <body className="brz" {...defaultThemeAttr}>{children}</body>
The MegaMenu will be fixed in editor: 
https://github.com/bagrinsergiu/blox-editor/issues/28027

2025-01-24 09:57 UTC, merged